### ISSUE TITLE
[Question] How does geofeather compare with pickle appled to gdf?

### ISSUE THREAD

**Issue by jwilson8767** [brendan-ward/geofeather#3]
I have been using pickle to solve temporary storage issues with geopandas dataframes with a good deal of success. What does geofeather do that pickle doesn't?

**Comment by brendan-ward** [comment]
@jwilson8767 I did not compare to `pickle`; I don't use `pickle` for anything.

After discovering the blazing speed of `feather` for tabular data, `geofeather` was a natural extension into the geospatial space.  I liked that it was optimized for fast I/O, column-oriented (so I could selectively read columns), and purported to have few to no data transformations required during I/O.  As a serialized format, I don't know that `pickle` offers any of those advantages.

[Work](https://github.com/geopandas/geopandas/pull/1180) is underway to use the very similar format `parquet` directly within `geopandas` - which brings similar (and additional) benefits to using `feather` as we are here.

There are a number of benchmarks available that compare `feather` to `pickle` and other formats; I'd suggest perusing those.  The only thing that `geofeather` adds on top of `feather` is specifically serializing / deserializing geometry objects.
