### ISSUE TITLE
Geopandas 0.70 PROJ 6

### ISSUE THREAD

**Issue by shakasom** [brendan-ward/geofeather#5]
With the new Proj 6 in Geopandas 0.70 release, you can not write to Geofeather. This is the error message.

`TypeError: Object of type CRS is not JSON serializable`

**Comment by brendan-ward** [comment]
Thanks @shakasom 

This was fixed in #4 on `master` - I'll push a new release up to PyPi now.

**Comment by shakasom** [comment]
Thanks @brendan-ward . That would be helpful.

**Comment by brendan-ward** [comment]
See https://github.com/brendan-ward/geofeather#030
Note that `to_shp` has been removed.

Reopen if this does not work correctly with your version of geopandas after upgrading geofeather.

**Comment by shakasom** [comment]
It works perfectly with the new releases.
